stages:
  - build

build job:
  stage: build
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=web
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install Flask Flask-SQLAlchemy SQLAlchemy