
FLASK_ADMIN_SWATCH = 'sandstone'
SECRET_KEY = 'secretkey'
SECURITY_PASSWORD_SALT = 'none'
SECURITY_POST_LOGIN_VIEW = '/admin/'
SECURITY_POST_LOGOUT_VIEW = '/admin/'
SECURITY_POST_REGISTER_VIEW = '/admin/'
SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
DATABASE = 'database.db'
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
